### ISSUE TITLE
File Error When Opening HPA Dataset with migrator.py on Windows 10

### ISSUE THREAD

**Issue by jackn11** [vaticle/biograkn-covid#25]
```
Opening HPA dataset...

  Downloading protein atlas data
100% [..........................................................................] 5596382 / 5596382  Finished downloading
Traceback (most recent call last):
  File "C:\Users\jackn\TypeDBBio\typedb-bio\migrator.py", line 61, in <module>
    migrate_protein_atlas(session, NUM_PA, args.num_threads, args.commit_batch)
  File "C:\Users\jackn\TypeDBBio\typedb-bio\Migrators\HumanProteinAtlas\HumanProteinAtlasMigrator.py", line 20, in migrate_protein_atlas
    tissue, raw_data = get_tissue_data(num)
  File "C:\Users\jackn\TypeDBBio\typedb-bio\Migrators\HumanProteinAtlas\HumanProteinAtlasMigrator.py", line 53, in get_tissue_data
    os.remove('Dataset/HumanProteinAtlas/normal_tissue.tsv')
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'Dataset/HumanProteinAtlas/normal_tissue.tsv'
```

**Comment by estkae** [comment]
This run only in Linux for Windows use wsl2
