### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by runfish5** [vaticle/biograkn-covid#32]
Dear friends,

I recognized there is a big update here on TypeDB Bio!

 I run into a problem when running `python loader.py`, it's coming from `loader.semmed.pipeline`.

ERROR:
```
Traceback (most recent call last):
  File "loader.py", line 13, in <module>
    from loader.semmed.pipeline import load_semmed
  File "/home/ubuntuds64/D_programs/typedb-bio/loader/semmed/pipeline.py", line 6, in <module>
    from loader.semmed.fetch import fetch_data
  File "/home/ubuntuds64/D_programs/typedb-bio/loader/semmed/fetch.py", line 11, in <module>
    def _fetch_metadata_from_api(pm_ids: list[str]) -> tuple[dict, int]:

```
- Operating system: Ubuntu (64-bit) (from Oracle VM VirtualBox)
- typedb version: 2.22.0
- typedb studio: 2.21.2

Thank you for your reply.

**Comment by james-whiteside** [comment]
Hi, what version of Python are you running? This looks like a common issue with `< 3.9` so I'd recommend upgrading to the latest version. If you are unable to, you could try one of the solutions [here](https://stackoverflow.com/a/75801151/21743154). Please let us know if this solves your issue.

**Comment by raven44099** [comment]
Many thanks! 

I updated to `python=3.10.13`, now I get a different error and whatever I do it doesn't leave.
I hope its okay to post this here or would you prefer when I opened a new Issue?

```pip install -r requirements.txt```
```
Traceback (most recent call last):
  File "/home/ubuntuds64/D_programs/typedb-bio/mynewenv/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/lib/python3/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/lib/python3/dist-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
ImportError: cannot import name 'html5lib' from 'pip._vendor' (/usr/lib/python3/dist-packages/pip/_vendor/__init__.py)
```
